LeafFoodDrops Config
====================
Comidas que pueden soltarse al romper hojas o arbustos

foods:
  - { item: BEEF, min: 1, max: 2 }
  - { item: PORKCHOP, min: 1, max: 2 }
  - { item: CHICKEN, min: 1, max: 2 }
  - { item: MUTTON, min: 1, max: 2 }
  - { item: COD, min: 1, max: 2 }
  - { item: SALMON, min: 1, max: 2 }
  - { item: POTATO, min: 1, max: 2 }
  - { item: APPLE, min: 1, max: 2 }

# Si activas esto en true, verás mensajes de depuración en consola.
debug-log: false